# Production Nginx image
FROM nginx:alpine

# Set working directory
WORKDIR /usr/share/nginx/html

# Remove default Nginx content
RUN rm -rf ./*

# Copy all frontend files
COPY ./ ./

# Copy custom Nginx config
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# Expose internal port
EXPOSE 80

# Run Nginx in foreground
CMD ["nginx", "-g", "daemon off;"]
