

services:

  frontend:
    build: ./frontend
    container_name: freeunitsconverter_frontend
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: freeunitsconverter_backend
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: freeunitsconverter_nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    restart: unless-stopped

  nginx_http:
    image: nginx:latest
    container_name: freeunitsconverter_nginx_http
    volumes:
      - ./nginx/http_only.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
    command: ["nginx", "-g", "daemon off;"]
    restart: "no"

  certbot:
    image: certbot/certbot
    container_name: freeunitsconverter_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: "no"
